# BigQuery (CEDAR)

### Installs

In [ ]:
%pip install --upgrade pip

In [ ]:
%pip install --upgrade google-cloud
%pip install --upgrade google-cloud-bigquery
%pip install --upgrade google-cloud-storage
%pip install requests
%pip install db-dtypes

### Imports

In [1]:
import json
import os
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account

### Connection

In [2]:
credentials = service_account.Credentials.from_service_account_file('key.json')
project_id = 'nissan-performance-dashboard'
client = bigquery.Client(credentials= credentials,project=project_id)
datasets = list(client.list_datasets())  # Make an API request.

### List datasets and tables

In [3]:
if datasets:
    print("Datasets in project {}:".format(project_id))
    for dataset in datasets:
        print("\t{}".format(dataset.dataset_id))
        tables = client.list_tables(dataset.dataset_id)

        print("Tables contained in '{}':".format(dataset.dataset_id))
        for table in tables:
            print("{}.{}.{}".format(table.project, table.dataset_id, table.table_id))

else:
    print("{} project does not contain any datasets.".format(project_id))

Datasets in project nissan-performance-dashboard:
	shared_views_arcadia
Tables contained in 'shared_views_arcadia':
nissan-performance-dashboard.shared_views_arcadia.dp_last_touch_marketing_channel
nissan-performance-dashboard.shared_views_arcadia.dp_last_touch_marketing_channel_models
nissan-performance-dashboard.shared_views_arcadia.dp_mobile_device_type
nissan-performance-dashboard.shared_views_arcadia.dp_mobile_device_type_models

In [6]:
df = client.query_and_wait('select * from shared_views_arcadia.dp_last_touch_marketing_channel').to_dataframe()
# for row in job.result():
#    print(row)

c:\ProgramData\Anaconda3\lib\site-packages\google\cloud\bigquery\table.py:2295: UserWarning: Unable to represent RANGE schema as struct using pandas ArrowDtype. Using `object` instead. To use ArrowDtype, use pandas >= 1.5 and pyarrow >= 10.0.1.
  warnings.warn(_RANGE_PYARROW_WARNING)
c:\ProgramData\Anaconda3\lib\site-packages\google\cloud\bigquery\table.py:2309: UserWarning: Unable to represent RANGE schema as struct using pandas ArrowDtype. Using `object` instead. To use ArrowDtype, use pandas >= 1.5 and pyarrow >= 10.0.1.
  warnings.warn(_RANGE_PYARROW_WARNING)
c:\ProgramData\Anaconda3\lib\site-packages\google\cloud\bigquery\table.py:2323: UserWarning: Unable to represent RANGE schema as struct using pandas ArrowDtype. Using `object` instead. To use ArrowDtype, use pandas >= 1.5 and pyarrow >= 10.0.1.
  warnings.warn(_RANGE_PYARROW_WARNING)

In [7]:
df

,row_date,brand,market,market_code,region_code,segment,category,region,channel,category_1,...,ecom_fc_page,ecom_trade_in_page,ecom_cancellation,ecom_qv,ecom_non_tds_leads_contact_us,unique_visitors,bounces,qualified_visits,leads_cedar_oce_others,leads_home_tools
0,2020-03-13,Nissan,Sweden,SE,AMIEO,None,Non-CP22,AMIEO,Organic,None,...,0,0,0,<NA>,0,20,<NA>,8,<NA>,<NA>
1,2020-03-13,Nissan,Sweden,SE,AMIEO,None,Non-CP22,AMIEO,Organic,None,...,0,0,0,<NA>,0,1,<NA>,1,<NA>,<NA>
2,2020-03-13,Nissan,Sweden,SE,AMIEO,None,Non-CP22,AMIEO,Paid,None,...,0,0,0,<NA>,0,2817,<NA>,1151,<NA>,<NA>
3,2020-03-13,Nissan,Sweden,SE,AMIEO,None,Non-CP22,AMIEO,Paid,None,...,0,0,0,<NA>,0,733,<NA>,175,<NA>,<NA>
4,2020-03-13,Nissan,Sweden,SE,AMIEO,None,Non-CP22,AMIEO,Organic,None,...,0,0,0,<NA>,0,66,<NA>,46,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73497,2018-01-17,Nissan,Sweden,SE,AMIEO,None,None,AMIEO,Paid,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
73498,2018-01-17,Nissan,Sweden,SE,AMIEO,None,None,AMIEO,Organic,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
73499,2018-01-17,Nissan,Sweden,SE,AMIEO,None,None,AMIEO,Paid,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
73500,2018-01-17,Nissan,Sweden,SE,AMIEO,None,None,AMIEO,Organic,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
73501,2018-01-17,Nissan,Sweden,SE,AMIEO,None,None,AMIEO,Organic,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>